package com.jakimenko.rainforecastbot.dto

data class Message(
    val message_id: Int,
    val from: User?,
    val chat: Chat?,
    val date: Int,
    val text: String?,
    val entities: Array<MessageEntity>?
)
//    val message_id: Int,
//    val from: User?,
//    val sender_chat: Chat?,
//    val date: Int,
//    val chat: Chat,
//    val forward_from: User?,
//    val forward_from_chat: Chat?,
//    val forward_from_message_id: Int?,
//    val forward_signature: String?,
//    val forward_sender_name: String?,
//    val forward_date: Int?,
//    val reply_to_message: Message?,
//    val via_bot: User?,
//    val edit_date: Int?,
//    val media_group_id: String?,
//    val author_signature: String?,
//    val text: String?,
//    val entities: Array<MessageEntity>?,
//    val animation: Animation?,
//    val audio: Audio?,
//    val document: Document?,
//    val photo: Array<PhotoSize>?,
//    val sticker: Sticker?,
//    val video: Video?,
//    val video_note: VideoNote?,
//    val voice: Voice?,
//    val caption: String?,
//    val caption_entities: Array<MessageEntity>?,
//    val contact: Contact?,
//    val dice: Dice?,
//    val game: Game?,
//    val poll: Poll?,
//    val venue: Venue?,
//    val location: Location?,
//    val new_chat_members: Array<User>?,
//    val left_chat_member: User?,
//    val new_chat_title: String?,
//    val new_chat_photo: Array<PhotoSize>?,
//    val delete_chat_photo: Boolean?,
//    val group_chat_created: Boolean?,
//    val supergroup_chat_created: Boolean?,
//    val channel_chat_created: Boolean?,
//    val message_auto_delete_timer_changed: MessageAutoDeleteTimerChanged?,
//    val migrate_to_chat_id: Int?,
//    val migrate_from_chat_id: Int?,
//    val pinned_message: Message?,
//    val invoice: Invoice?,
//    val successful_payment: SuccessfulPayment?,
//    val connected_website: String?,
//    val passport_data: PassportData?,
//    val proximity_alert_triggered: ProximityAlertTriggered?,
//    val voice_chat_scheduled: VoiceChatScheduled?,
//    val voice_chat_started: VoiceChatStarted?,
//    val voice_chat_ended: VoiceChatEnded?,
//    val voice_chat_participants_invited: VoiceChatParticipantsInvited?,
//    val reply_markup: InlineKeyboardMarkup?

